name: Update Issue Status in GitHub Project

on:
  pull_request:
    types:
      - closed

jobs:
  update-issue-status:
    if: github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest

    steps:
      - name: Extract issue number from branch name
        id: extract-issue
        run: |
          echo "::set-output name=issue_number::$(echo '${{ github.event.pull_request.head.ref }}' | sed -E 's/^feature\/([0-9]+)-.*/\1/')"

      - name: Debug issue number
        run: |
          echo "Extracted issue number: ${{ steps.extract-issue.outputs.issue_number }}"

      - name: Validate issue number
        id: validate-issue
        run: |
          if [[ -z "${{ steps.extract-issue.outputs.issue_number }}" ]]; then
            echo "No valid issue number found. Skipping.";
            exit 0;
          fi

      - name: Update issue status in GitHub Project
        if: success() && steps.validate-issue.conclusion == 'success'
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = parseInt(process.env.ISSUE_NUMBER, 10);
            if (!issueNumber) {
              console.log('No valid issue number found. Exiting.');
              return;
            }

            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
            });

            console.log(`Found issue #${issueNumber}: ${issue.title}`);
            
            const { data: projects } = await github.rest.projects.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const project = projects.find(p => p.name === 'Task list' || p.id === 2);
            if (!project) {
              console.log('Project not found');
              return;
            }

            const column = project.columns.find(c => c.name === 'In Develop');
            if (!column) {
              console.log('Column "In Develop" not found');
              return;
            }

            const { data: cards } = await github.rest.projects.listCards({
              column_id: column.id,
            });

            const issueCard = cards.find(card => card.content_url.includes(`/issues/${issueNumber}`));
            if (!issueCard) {
              console.log(`No card found for issue #${issueNumber}`);
              return;
            }

            await github.rest.projects.moveCard({
              card_id: issueCard.id,
              position: 'top',
              column_id: column.id,
            });

            console.log(`Issue #${issueNumber} moved to column "In Develop".`);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ steps.extract-issue.outputs.issue_number }}